---
layout: default
title: about me
---
#+PROPERTY: cache yes
#+PROPERTY: results output
#+OPTIONS: toc:nil
#+PROPERTY: exports code

* {{ page.title }}

I finished my doctorate in Computer Science at [[http://www.inf.puc-rio.br][PUC-Rio]] (2010). I am a
senior research scientist at [[http://researcher.ibm.com/person/br-alexrad ][IBM Research]] (Brazil Lab) and adjunct
professor at the [[http://emap.fgv.br][Applied Mathematics Department]] from Getulio Vargas
Foundation (Rio de Janeiro, Brazil).

I wrote over 100 papers published in peer-reviewed journals and
international conferences in: logic, proof theory, knowledge
representation and reasoning, language resources, computational
linguistics, and type theory. I participate as a member of many
program committees of regular conferences like ACL, COLING, LREC, and
others. I am also a board member of the Global WordNet Association and
coordinated the [[http://cepln.github.io][CE-PLN]] between 2017-219. I collaborate on maintaining
many language resources and developing applications using these
resources for 'deep' linguistic processing of human languages.

During my Ph.D., I made two international fellowships at Microsoft
Research and SRI International. At MSR, in 2008, he worked with the [[https://en.wikipedia.org/wiki/Z3_Theorem_Prover][Z3
SMT Solver]] team (Leonardo de Moura and Nikolaj Bjørner) developing a
distributed environment for testing and optimizations of Z3. At [[http://www.sri.com/][SRI
International]], in 2009, he worked under the supervision of Natarajan
Shankar. In my thesis, I proposed new deduction systems for
description logics under the supervision of Edward Hermann Haeusler,
published by Springer with the title [[https://www.amazon.com/Theory-Description-SpringerBriefs-Computer-Science-ebook/dp/B00A9YGJR0][A proof theory for Description
Logics]] in the Springer Briefs series.

You can find more information at:

 - [[https://research.ibm.com/people/alexandre-rademaker]]
 - [[http://www.informatik.uni-trier.de/~ley/db/indices/a-tree/r/Rademaker:Alexandre.html][Publications at DBLP]]
 - [[http://scholar.google.com/citations?user=SWz6BjIAAAAJ]]
 - [[http://academic.research.microsoft.com/Author/2751793]]
 - [[http://www.researchgate.net/profile/Alexandre_Rademaker/]]
 - [[http://fgv.academia.edu/AlexandreRademaker]]
 - [[http://lattes.cnpq.br/0675365413696898][Curriculum Lattes (Portuguese)]]
 - [[http://twitter.com/arademaker]]
  
