---
layout: default
title: about me
---
#+PROPERTY: cache yes
#+PROPERTY: results output
#+OPTIONS: toc:nil
#+PROPERTY: exports code

* {{ page.title }}

Alexandre is a Research Staff Member in the [[https://ibm.biz/brl-nrs][Natural Resources
Solutions group]] at IBM Research – Brazil. He joined IBM in
December 2012. Alexandre is also an adjunct professor at the [[http://emap.fgv.br][Applied
Mathematics School of Getulio Vargas Foundation]] (EMAp/FGV). Alexandre
has taught many graduate and undergraduate courses: logic, data
structures, programming, formal languages, and automata theory.

Alexandre holds a Ph.D. (2010) in Computer Science from Pontifical
Catholic University of Rio de Janeiro (PUC-Rio) and M.Sc. (2005) in
Computer Science from Fluminense Federal University, and B.Sc. (2001)
in Computer Science from Federal University of Rio de Janeiro.

During his Ph.D., Alexandre was an international fellow at Microsoft
Research and SRI International. At MSR, in 2008, he worked with the [[http://research.microsoft.com/en-us/um/redmond/projects/z3/people.html][Z3
SMT Solver]] team (Leonardo de Moura and Nikolaj Bjørner) developing a
distributed environment for testing and optimizations of Z3. At [[http://www.sri.com/][SRI
International]], in 2009, he worked under the supervision of Natarajan
Shankar in different research projects including the preliminary
formalization of ALC deduction systems in PVS. Alexandre participated
in several research projects like MIST (using natural language
processing and description logics for Knowledge modeling), ANUBIS
(database consistency check) and Ontology and Context (investigating
the problem of ontology alignment). In his thesis, we proposed new
deduction systems for description logics under the supervision of
Edward Hermann Haeusler, published by Springer with the title [[https://www.amazon.com/Theory-Description-SpringerBriefs-Computer-Science-ebook/dp/B00A9YGJR0/ref=sr_1_1?ie=UTF8&qid=1522712247&sr=8-1&keywords=alexandre+rademaker][A proof
theory for Description Logics]] in 2012 as a book of the series Springer
Briefs.

Alexandre is the author/co-author of more than 70 papers published in
peer-reviewed journals and international conferences. His areas of
expertise and interesting are logic, proof theory, knowledge
representation and reasoning, type theory, computational semantics,
lexical resources and computational grammars.

You can find more information at:

 - [[http://researcher.ibm.com/person/br-alexrad]]
 - [[http://www.informatik.uni-trier.de/~ley/db/indices/a-tree/r/Rademaker:Alexandre.html][Publications at DBLP]]
 - [[http://scholar.google.com/citations?user=SWz6BjIAAAAJ]]
 - [[http://academic.research.microsoft.com/Author/2751793]]
 - [[http://www.researchgate.net/profile/Alexandre_Rademaker/]]
 - [[http://fgv.academia.edu/AlexandreRademaker]]
 - [[http://lattes.cnpq.br/0675365413696898][Curriculum Lattes (Portuguese)]]
 - [[http://facebook.com/alexandre.rademaker]]
 - [[http://twitter.com/arademaker]]
  
* Organizational activities

- Board member of the [[http://www.globalwordnet.org][Global WordNet Association]].
  
