---
layout: default
title: Advising and Mentoring
---
#+PROPERTY: cache yes
#+PROPERTY: results output
#+OPTIONS: toc:nil
#+PROPERTY: exports code

* {{ page.title }}

* Current Students

- Yuri Luis Faria (undergrad)
- Fredson Silva (undergrad)
- Cristiana Nogueira (undergrad)
- Lucas Ribeiro (masters)
- Alexandre Tessarolo (masters)

* Past Students

** Alessandra Corrêa

Alessandra is a dual degree student in Law and Applied Mathematics at
FGV. While in Law School, she spent a semester at New York University
(NYU) and received a research scholarship to study cognitive biases in
the behavior of judges. At EMAp, she was part in the project to
develop a system to pass the OAB Exam.

** Bruno Cuconato

Bruno was a MSc student at EMAp/FGV. he likes programming languages
and logic, and he worked in a Portuguese computational grammar under
the GF formalism under this masters under supervision of Alexandre.

** Guilherme Passos

Guilherme Paulino Passos is a Master's student in Computer Science at
PESC/COPPE, under co-supervision of Alexandre Rademaker and
supervision of Gerson Zaverucha. Guilherme worked in the formal
representation of syntactical analyses of natural language, for
improving the quality of linguistic datasets and detecting errors in
data-driven parsing. In the past, he worked with Alexandre in projects
on Formal Verification of Description Logics, and Computational
Semantics. Guilherme holds a Bachelor's Degree in Law and a Bachelor's
Degree in Applied Mathematics and his interests include Artificial
Intelligence & Law, Natural Language Understanding, Logical and
Relational Machine Learning, and Knowledge Representation and
Reasoning.

** Henrique Muniz

He had worked with many projects related to NLP: (a) a Common Lisp
library for processing CoNLL-U files; (b) web interface for the DHBB
data visualization; (c) wordnet expansion for Geo Science domain. At
IBM he worked on projects related with information extraction for oil
and gas domain.

** Pedro Delfino

Pedro holds a Bachelor's Degree in Law. Pedro worked on the
development of a system to pass in the OAB Exams.

