
gems: ['jekyll/scholar','rdiscount']

highlighter: rouge
markdown: kramdown

scholar:
  style: chicago-author-date
  locale: en

  sort_by: none
  order: reverse

  source: ./_bibliography
  bibliography: rademaker.bib

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"  
